import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from "next/head";
import styles from "../styles/Home.module.css";

function MyApp({Component, pageProps}: AppProps) {
  return <div className={styles.container}>
    <Head>
      <title>Wiki</title>
      <meta name="description" content="Generated by create next app"/>
      <meta httpEquiv="content-language" content="en"/>
      {
        // <link rel="icon" href="/favicon.ico"/>
      }
    </Head>
    <div className={styles.navbar}>
      <h1 className={styles.title}><a href={"/"}>Wiki</a></h1>
    </div>
    <main className={styles.main}>
      <Component {...pageProps} />
    </main>

    <footer className={styles.footer}>
      <a href={"/"}>Home</a>
      {" - "}
      <a href="https://www.github.com/haynesgt/nextwiki">Source Code</a>
    </footer>
  </div>;
}

export default MyApp
