import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {xmur3, array, randomParagraph, srand} from "../_util";

srand();

const pages = array(10).map((_, i) => ({
  id: i,
  data: {
    title: randomParagraph(5),
    content: randomParagraph(200),
  }
}));

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wiki</title>
        <meta name="description" content="Generated by create next app"/>
        <meta httpEquiv="content-language" content="en"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <div className={styles.navbar}>
        <h1 className={styles.title}>Wiki</h1>
      </div>

      <main className={styles.main}>
        {
          pages.map(({id, data: {title, content}}) =>
            <div key={id} className={styles.pageSummary}>
              <b>{title}</b>{' - '}
              <span className={styles.edit}>
                <a className={"link"}>Edit</a>
              </span>
              {content}
            </div>
          )
        }
      </main>

      <footer className={styles.footer}>
        <a href="https://www.github.com/haynesgt/nextwiki">Source Code</a>
      </footer>
    </div>
  )
}

export default Home
